### ISSUE TITLE
Failed to load the slack-atom package

### ISSUE THREAD

**Issue by curtisblackwell** [pavloo/slack-atom#17]
As soon as I tried installing this, I got this error.

> Cannot read property 'prototype' of undefined
> TypeError: Cannot read property 'prototype' of undefined
>     at __extends (.atom/packages/slack-atom/lib/slack-atom-view.coffee:1:1)
>     at .atom/packages/slack-atom/lib/slack-atom-view.coffee:8:3
>     at Object.<anonymous> (.atom/packages/slack-atom/lib/slack-atom-view.coffee:8:3)
>     at Object.<anonymous> (.atom/packages/slack-atom/lib/slack-atom-view.coffee:1:1)
>     at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
>     at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)

**Comment by curtisblackwell** [comment]
Just saw a bunch of duplicates of this, so I'll close this. (The auto-file feature in Atom wasn't working.)
