### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by unixelias** [pavloo/slack-atom#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [slack-atom](https://github.com/sol1dus/slack-atom) package, v0.2.0

### Stack Trace

Failed to load the slack-atom package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/elias/.atom/packages/slack-atom/lib/slack-atom-view.coffee:1:1)
    at /home/elias/.atom/packages/slack-atom/lib/slack-atom-view.coffee:8:3
    at Object.<anonymous> (/home/elias/.atom/packages/slack-atom/lib/slack-atom-view.coffee:8:3)
    at Object.<anonymous> (/home/elias/.atom/packages/slack-atom/lib/slack-atom-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/elias/.atom/packages/slack-atom/lib/slack-atom.coffee:1:17)
    at Object.<anonymous> (/home/elias/.atom/packages/slack-atom/lib/slack-atom.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:536:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:55.5.0 AtomPair:invite over slack (div.panels-item)
     -1:16.7.0 slack-chat:toggle (atom-text-editor.editor.mini.is-focused)
     -0:19.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-slack-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.10
pigments, v0.29.2
slack-atom, v0.2.0
slack-chat, v3.4.2

# Dev
No dev packages
```

**Comment by pavloo** [comment]
@unixelias thanks for the bug report, but unfortunately I went back to using `emacs` and don't use atom and this package anymore. if you want to make a fix, PRs a welcome.
